// Generated by tests/expected_draws.py from the definitions in src/sim/SPEC.md. Do not edit;
// regenerate with: python3 tests/expected_draws.py > tests/expected_draws.h
#ifndef TPJ_TESTS_EXPECTED_DRAWS_H
#define TPJ_TESTS_EXPECTED_DRAWS_H

#include "sim/draw.h"
#include "sim/entity_key.h"

#include <array>
#include <stddef.h>
#include <stdint.h>

namespace tpj::test {

struct ExpectedDraw {
  DrawKey Key;
  uint64_t Bits = 0;
  double Uniform = 0.0;
  size_t IntegerPick = 0;
  size_t DoublePick = 0;
};

inline constexpr std::array<uint64_t, 5> EXPECTED_DRAW_INTEGER_WEIGHTS = {7, 0, 12, 3, 9};
inline constexpr std::array<double, 4> EXPECTED_DRAW_DOUBLE_WEIGHTS = {0.1, 0.0, 0.7, 0.2};

inline constexpr std::array<ExpectedDraw, 10> EXPECTED_DRAWS = {{
    // Every word zero.
    {.Key = {.Seed = 0x0000000000000000ULL,
             .Entity = EntityKey{0x0000000000000000ULL},
             .Purpose = 0x0000000000000000ULL,
             .Tick = 0x0000000000000000ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0x7d19c361a3548205ULL,
     .Uniform = 0x1.f4670d868d520p-2,
     .IntegerPick = 2,
     .DoublePick = 2},
    // A typical key.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x0000000000000007ULL},
             .Purpose = 0x0123456789abcdefULL,
             .Tick = 0x0000000000000bb8ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0xaaabe30736af325aULL,
     .Uniform = 0x1.5557c60e6d5e6p-1,
     .IntegerPick = 3,
     .DoublePick = 2},
    // The seed changed.
    {.Key = {.Seed = 0x000000000000303aULL,
             .Entity = EntityKey{0x0000000000000007ULL},
             .Purpose = 0x0123456789abcdefULL,
             .Tick = 0x0000000000000bb8ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0x0a84522c347b4417ULL,
     .Uniform = 0x1.508a45868f680p-5,
     .IntegerPick = 0,
     .DoublePick = 0},
    // The entity changed to a derived-range key.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x8000000000000007ULL},
             .Purpose = 0x0123456789abcdefULL,
             .Tick = 0x0000000000000bb8ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0x30d69da6509e5f6dULL,
     .Uniform = 0x1.86b4ed3284f2cp-3,
     .IntegerPick = 0,
     .DoublePick = 2},
    // The purpose changed.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x0000000000000007ULL},
             .Purpose = 0xfedcba9876543210ULL,
             .Tick = 0x0000000000000bb8ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0x501c4c287558cb7eULL,
     .Uniform = 0x1.407130a1d5632p-2,
     .IntegerPick = 2,
     .DoublePick = 2},
    // The tick changed.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x0000000000000007ULL},
             .Purpose = 0x0123456789abcdefULL,
             .Tick = 0x0000000000000bb9ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0xef0d0f0596ec5b3cULL,
     .Uniform = 0x1.de1a1e0b2dd8bp-1,
     .IntegerPick = 4,
     .DoublePick = 3},
    // The index changed.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x0000000000000007ULL},
             .Purpose = 0x0123456789abcdefULL,
             .Tick = 0x0000000000000bb8ULL,
             .Index = 0x0000000000000001ULL},
     .Bits = 0x48a15c74d5ddc884ULL,
     .Uniform = 0x1.228571d357772p-2,
     .IntegerPick = 2,
     .DoublePick = 2},
    // Every word at its maximum.
    {.Key = {.Seed = 0xffffffffffffffffULL,
             .Entity = EntityKey{0xffffffffffffffffULL},
             .Purpose = 0xffffffffffffffffULL,
             .Tick = 0xffffffffffffffffULL,
             .Index = 0xffffffffffffffffULL},
     .Bits = 0x3665503d5bbedaddULL,
     .Uniform = 0x1.b32a81eaddf6cp-3,
     .IntegerPick = 0,
     .DoublePick = 2},
    // A value in the first word only.
    {.Key = {.Seed = 0x0000000000003039ULL,
             .Entity = EntityKey{0x0000000000000000ULL},
             .Purpose = 0x0000000000000000ULL,
             .Tick = 0x0000000000000000ULL,
             .Index = 0x0000000000000000ULL},
     .Bits = 0x18de66021c135aacULL,
     .Uniform = 0x1.8de66021c1358p-4,
     .IntegerPick = 0,
     .DoublePick = 0},
    // The same value in the last word only.
    {.Key = {.Seed = 0x0000000000000000ULL,
             .Entity = EntityKey{0x0000000000000000ULL},
             .Purpose = 0x0000000000000000ULL,
             .Tick = 0x0000000000000000ULL,
             .Index = 0x0000000000003039ULL},
     .Bits = 0x77774fdbbaec88d4ULL,
     .Uniform = 0x1.dddd3f6eebb22p-2,
     .IntegerPick = 2,
     .DoublePick = 2},
}};

} // namespace tpj::test

#endif
