#!/usr/bin/env python3
"""Writes tests/sim/support/expected_draws.h: expected keyed draws, computed from src/sim/SPEC.md
alone.

This is an implementation of the draw definitions independent of tpj_sim. Python's integers are
exact and its floats are IEEE doubles rounded to nearest, so every value here is the one the
specification defines. Regenerate with:

    python3 tests/sim/support/expected_draws.py > tests/sim/support/expected_draws.h
"""

MASK = (1 << 64) - 1
GAMMA = 0x9E3779B97F4A7C15
HASHER_START = 0x6A09E667F3BCC909


def mix64(x):
    x = ((x ^ (x >> 30)) * 0xBF58476D1CE4E5B9) & MASK
    x = ((x ^ (x >> 27)) * 0x94D049BB133111EB) & MASK
    return x ^ (x >> 31)


def draw_bits(key):
    state = HASHER_START
    for word in key:  # seed, entity, purpose, tick, index, in that order
        state = mix64(((state ^ word) + GAMMA) & MASK)
    return state


def draw_uniform(bits):
    return (bits >> 11) * 2.0**-53


def pick_integer(bits, weights):
    total = sum(weights)
    r = (bits * total) >> 64
    running = 0
    for i, w in enumerate(weights):
        running += w
        if running > r:
            return i
    raise AssertionError("no index picked")


def pick_double(bits, weights):
    total = 0.0
    for w in weights:
        total += w
    target = draw_uniform(bits) * total
    running = 0.0
    for i, w in enumerate(weights):
        running += w
        if running > target:
            return i
    raise AssertionError("no index picked")


# A total that is not a power of two, and a zero weight inside the list.
INTEGER_WEIGHTS = [7, 0, 12, 3, 9]
# Weights whose in-order sum rounds (0.1 + 0.7 + 0.2 is below 1), and a zero weight inside.
DOUBLE_WEIGHTS = [0.1, 0.0, 0.7, 0.2]

BASE = (12345, 7, 0x0123456789ABCDEF, 3000, 0)

# (reason, (seed, entity, purpose, tick, index))
KEYS = [
    ("every word zero", (0, 0, 0, 0, 0)),
    ("a typical key", BASE),
    ("the seed changed", (12346, *BASE[1:])),
    ("the entity changed to a derived-range key", (BASE[0], 0x8000000000000007, *BASE[2:])),
    ("the purpose changed", (*BASE[:2], 0xFEDCBA9876543210, *BASE[3:])),
    ("the tick changed", (*BASE[:3], 3001, BASE[4])),
    ("the index changed", (*BASE[:4], 1)),
    ("every word at its maximum", (MASK, MASK, MASK, MASK, MASK)),
    ("a value in the first word only", (12345, 0, 0, 0, 0)),
    ("the same value in the last word only", (0, 0, 0, 0, 12345)),
]


def main():
    print("// Generated by tests/sim/support/expected_draws.py from the definitions in src/sim/SPEC.md.")
    print("// Do not edit; regenerate from the repository root with:")
    print("// python3 tests/sim/support/expected_draws.py > tests/sim/support/expected_draws.h")
    print("#ifndef TPJ_TESTS_SIM_SUPPORT_EXPECTED_DRAWS_H")
    print("#define TPJ_TESTS_SIM_SUPPORT_EXPECTED_DRAWS_H")
    print()
    print('#include "sim/draw.h"')
    print('#include "sim/entity_key.h"')
    print()
    print("#include <array>")
    print("#include <stddef.h>")
    print("#include <stdint.h>")
    print()
    print("namespace tpj::test {")
    print()
    print("struct ExpectedDraw {")
    print("  DrawKey Key;")
    print("  uint64_t Bits = 0;")
    print("  double Uniform = 0.0;")
    print("  size_t IntegerPick = 0;")
    print("  size_t DoublePick = 0;")
    print("};")
    print()
    ints = ", ".join(f"{w}" for w in INTEGER_WEIGHTS)
    doubles = ", ".join(repr(w) for w in DOUBLE_WEIGHTS)
    print(f"inline constexpr std::array<uint64_t, {len(INTEGER_WEIGHTS)}> "
          f"EXPECTED_DRAW_INTEGER_WEIGHTS = {{{ints}}};")
    print(f"inline constexpr std::array<double, {len(DOUBLE_WEIGHTS)}> "
          f"EXPECTED_DRAW_DOUBLE_WEIGHTS = {{{doubles}}};")
    print()
    print(f"inline constexpr std::array<ExpectedDraw, {len(KEYS)}> EXPECTED_DRAWS = {{{{")
    for reason, key in KEYS:
        bits = draw_bits(key)
        seed, entity, purpose, tick, index = key
        print(f"    // {reason[0].upper()}{reason[1:]}.")
        print(f"    {{.Key = {{.Seed = 0x{seed:016x}ULL,")
        print(f"             .Entity = EntityKey{{0x{entity:016x}ULL}},")
        print(f"             .Purpose = 0x{purpose:016x}ULL,")
        print(f"             .Tick = 0x{tick:016x}ULL,")
        print(f"             .Index = 0x{index:016x}ULL}},")
        print(f"     .Bits = 0x{bits:016x}ULL,")
        print(f"     .Uniform = {draw_uniform(bits).hex()},")
        print(f"     .IntegerPick = {pick_integer(bits, INTEGER_WEIGHTS)},")
        print(f"     .DoublePick = {pick_double(bits, DOUBLE_WEIGHTS)}}},")
    print("}};")
    print()
    print("} // namespace tpj::test")
    print()
    print("#endif")


if __name__ == "__main__":
    main()
