# Fails when the code under src and tests breaks the layers a table declares (decision 0027). Each
# finding is one line, with paths relative to ROOT:
#
#     <file> in <unit> includes <header> in <unit>, which is not below it
#     <file> is in no layer
#     <unit> holds no file
#     <unit> is listed more than once
#
# A unit of the table is written src/<unit>, a test of module m, under tests/m, as tests/m, and a
# file under tests/integration as tests/integration.
#
# Usage: cmake -DROOT=<tree> -DLAYERS=<table> -P check_layers.cmake

cmake_minimum_required(VERSION 3.28)

foreach(required ROOT LAYERS)
    if(NOT ${required})
        message(FATAL_ERROR "usage: cmake -DROOT=<tree> -DLAYERS=<table> -P check_layers.cmake")
    endif()
endforeach()

# ROOT as an absolute, normalized path with no trailing separator, so that walks up from a file
# stop at it.
cmake_path(ABSOLUTE_PATH ROOT NORMALIZE)
string(REGEX REPLACE "(.)/$" "\\1" ROOT "${ROOT}")
set(SRC "${ROOT}/src")
set(TESTS "${ROOT}/tests")

if(NOT EXISTS "${LAYERS}" OR IS_DIRECTORY "${LAYERS}")
    message(FATAL_ERROR "Cannot read the layer table ${LAYERS}")
endif()

set(findings "")

# The table: one layer per line, lowest first, its units separated by blanks. units and
# unitLayers are parallel lists; modules and moduleLayers hold each module's highest layer.
set(units "")
set(unitLayers "")
set(modules "")
set(moduleLayers "")
set(layer 0)
file(STRINGS "${LAYERS}" tableLines)
foreach(line IN LISTS tableLines)
    if(line MATCHES "^[ \t]*(#|$)")
        continue()
    endif()
    string(REGEX MATCHALL "[^ \t]+" lineUnits "${line}")
    foreach(unit IN LISTS lineUnits)
        if(unit IN_LIST units)
            list(APPEND findings "src/${unit} is listed more than once")
            continue()
        endif()
        list(APPEND units "${unit}")
        list(APPEND unitLayers ${layer})
        string(REGEX REPLACE "/.*" "" module "${unit}")
        list(FIND modules "${module}" moduleIndex)
        if(moduleIndex EQUAL -1)
            list(APPEND modules "${module}")
            list(APPEND moduleLayers ${layer})
        else()
            list(REMOVE_AT moduleLayers ${moduleIndex})
            list(INSERT moduleLayers ${moduleIndex} ${layer})
        endif()
    endforeach()
    math(EXPR layer "${layer} + 1")
endforeach()
# tests/integration sits above every layer.
set(INTEGRATION_LAYER ${layer})

# Sets placedLabel and placedLayer in the caller to the unit and layer of the file at path, and
# placedHolders to every unit of the table that holds it. The label is empty for a file in no
# layer.
function(place path)
    set(label "")
    set(layerOfFile "")
    set(holders "")
    cmake_path(IS_PREFIX SRC "${path}" NORMALIZE inSrc)
    cmake_path(IS_PREFIX TESTS "${path}" NORMALIZE inTests)
    if(inSrc)
        # A file unit is the most specific, then the directory unit with the most components, and
        # of two for the same directory the /* unit.
        cmake_path(GET path PARENT_PATH parent)
        set(stem "${path}")
        cmake_path(REMOVE_EXTENSION stem LAST_ONLY)
        set(bestRank -1)
        set(index 0)
        foreach(unit IN LISTS units)
            set(rank -1)
            if(unit MATCHES "^(.*)/\\*$")
                set(directory "${SRC}/${CMAKE_MATCH_1}")
                if(parent STREQUAL directory)
                    string(REGEX MATCHALL "[^/]+" components "${CMAKE_MATCH_1}")
                    list(LENGTH components count)
                    math(EXPR rank "${count} * 2 + 1")
                endif()
            else()
                set(unitPath "${SRC}/${unit}")
                string(REGEX MATCHALL "[^/]+" components "${unit}")
                list(LENGTH components count)
                if(stem STREQUAL unitPath)
                    math(EXPR rank "1000000 + ${count}")
                else()
                    cmake_path(IS_PREFIX unitPath "${path}" NORMALIZE holds)
                    if(holds)
                        math(EXPR rank "${count} * 2")
                    endif()
                endif()
            endif()
            if(rank GREATER -1)
                list(APPEND holders "${unit}")
                if(rank GREATER bestRank)
                    set(bestRank ${rank})
                    set(label "src/${unit}")
                    list(GET unitLayers ${index} layerOfFile)
                endif()
            endif()
            math(EXPR index "${index} + 1")
        endforeach()
    elseif(inTests)
        cmake_path(RELATIVE_PATH path BASE_DIRECTORY "${TESTS}" OUTPUT_VARIABLE underTests)
        string(REGEX MATCHALL "[^/]+" components "${underTests}")
        list(LENGTH components count)
        if(count GREATER 1)
            list(GET components 0 module)
            list(FIND modules "${module}" moduleIndex)
            if(module STREQUAL "integration")
                set(label "tests/integration")
                set(layerOfFile ${INTEGRATION_LAYER})
            elseif(NOT moduleIndex EQUAL -1)
                set(label "tests/${module}")
                list(GET moduleLayers ${moduleIndex} layerOfFile)
            endif()
        endif()
    endif()
    set(placedLabel "${label}" PARENT_SCOPE)
    set(placedLayer "${layerOfFile}" PARENT_SCOPE)
    set(placedHolders "${holders}" PARENT_SCOPE)
endfunction()

# True in the caller's allowed when a file with the first label and layer may include a header
# with the second.
function(may_include fileLabel fileLayer headerLabel headerLayer)
    set(result FALSE)
    if(headerLabel STREQUAL fileLabel OR headerLayer LESS fileLayer)
        set(result TRUE)
    elseif(fileLabel STREQUAL "tests/integration")
        set(result TRUE)
    elseif(fileLabel MATCHES "^tests/(.+)$")
        # A module's tests may include any of the module's units and its other tests.
        set(module "${CMAKE_MATCH_1}")
        if(headerLabel STREQUAL "tests/${module}" OR headerLabel MATCHES "^src/${module}(/|$)")
            set(result TRUE)
        endif()
    endif()
    set(allowed ${result} PARENT_SCOPE)
endfunction()

file(GLOB_RECURSE files LIST_DIRECTORIES false
    "${SRC}/*.h" "${SRC}/*.cpp" "${TESTS}/*.h" "${TESTS}/*.cpp")
list(SORT files)

# Each scanned file's label and layer, parallel to files, so includes of it need no placing again.
set(fileLabels "")
set(fileLayers "")
set(heldUnits "")
foreach(file IN LISTS files)
    place("${file}")
    list(APPEND heldUnits ${placedHolders})
    if(placedLabel STREQUAL "")
        cmake_path(RELATIVE_PATH file BASE_DIRECTORY "${ROOT}" OUTPUT_VARIABLE fileText)
        list(APPEND findings "${fileText} is in no layer")
        list(APPEND fileLabels "-")
        list(APPEND fileLayers "-")
    else()
        list(APPEND fileLabels "${placedLabel}")
        list(APPEND fileLayers "${placedLayer}")
    endif()
endforeach()

foreach(unit IN LISTS units)
    if(NOT unit IN_LIST heldUnits)
        list(APPEND findings "src/${unit} holds no file")
    endif()
endforeach()

set(INCLUDE_LINE "^[ \t]*#[ \t]*include[ \t]*[\"<]([^\">]+)[\">]")
set(index -1)
foreach(file IN LISTS files)
    math(EXPR index "${index} + 1")
    list(GET fileLabels ${index} fileLabel)
    if(fileLabel STREQUAL "-")
        continue()
    endif()
    list(GET fileLayers ${index} fileLayer)

    # An include is read against the file's directory, every directory above it up to ROOT, and
    # ROOT/src: a superset of every target's search path, so it is checked against every file it
    # could name.
    set(bases "${SRC}")
    cmake_path(GET file PARENT_PATH base)
    while(TRUE)
        list(APPEND bases "${base}")
        if(base STREQUAL ROOT)
            break()
        endif()
        cmake_path(GET base PARENT_PATH base)
    endwhile()

    file(STRINGS "${file}" includes REGEX "${INCLUDE_LINE}")
    foreach(line IN LISTS includes)
        string(REGEX MATCH "${INCLUDE_LINE}" match "${line}")
        set(path "${CMAKE_MATCH_1}")
        foreach(base IN LISTS bases)
            set(header "${base}/${path}")
            cmake_path(NORMAL_PATH header)
            cmake_path(IS_PREFIX SRC "${header}" NORMALIZE inSrc)
            cmake_path(IS_PREFIX TESTS "${header}" NORMALIZE inTests)
            if(NOT (inSrc OR inTests) OR NOT EXISTS "${header}" OR IS_DIRECTORY "${header}")
                continue()
            endif()
            list(FIND files "${header}" headerIndex)
            if(headerIndex EQUAL -1)
                place("${header}")
                set(headerLabel "${placedLabel}")
                set(headerLayer "${placedLayer}")
            else()
                list(GET fileLabels ${headerIndex} headerLabel)
                list(GET fileLayers ${headerIndex} headerLayer)
            endif()
            # A header in no layer is reported as a file, not at each include of it.
            if(headerLabel STREQUAL "" OR headerLabel STREQUAL "-")
                continue()
            endif()
            may_include("${fileLabel}" "${fileLayer}" "${headerLabel}" "${headerLayer}")
            if(NOT allowed)
                cmake_path(RELATIVE_PATH file BASE_DIRECTORY "${ROOT}" OUTPUT_VARIABLE fileText)
                cmake_path(RELATIVE_PATH header BASE_DIRECTORY "${ROOT}" OUTPUT_VARIABLE headerText)
                string(CONCAT finding "${fileText} in ${fileLabel} includes ${headerText} in "
                    "${headerLabel}, which is not below it")
                list(APPEND findings "${finding}")
            endif()
        endforeach()
    endforeach()
endforeach()

# NOTICE prints each line as it is; FATAL_ERROR would wrap long ones.
if(findings)
    list(REMOVE_DUPLICATES findings)
    foreach(line IN LISTS findings)
        message(NOTICE "${line}")
    endforeach()
    message(FATAL_ERROR "Includes break the layers in ${LAYERS}.")
endif()
message(STATUS "${ROOT} follows the layers in ${LAYERS}")
